export const ADD_DATA = 'ADD_DATA'
export const POST_PREDICTION = 'POST_PREDICTION'
export const RESET_INPUT_DATA = 'RESET_INPUT_DATA'
export const SHOW_SPINNER = 'SHOW_SPINNER'
export const SET_RATING = "SET_RATING"
